name: todolist
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.4.2
  intl: ^0.19.0
  flutter_datetime_picker_plus: ^2.2.0
  animate_do: ^3.3.4
  flutter_beautiful_popup: ^1.7.0
  panara_dialogs: ^0.1.5
  lottie: ^3.1.2
  ftoast: ^2.0.0
  flutter_slider_drawer: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/lottie/



